src/Entity/Movie.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MovieRepository")
 */
class Movie
{
    /**
     * @ORM\Id()
     * @ORM\Column(type="string", length=255)
     */
    private $omdb_id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $seen;

        /**
     * @ORM\Column(type="boolean")
     */
    private $toSee;

         /**
     * @ORM\Column(type="boolean")
     */
    private $notSeen;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $year;

    private $summary;


    public function getOmdbId(): ?string
    {
        return $this->omdb_id;
    }

    public function setOmdbId(string $omdb_id): self
    {
        $this->omdb_id = $omdb_id;

        return $this;
    }

    public function getSeen(): ?string
    {
        return $this->seen;
    }

    public function setSeen(?string $seen): self
    {
        $this->seen = $seen;

        return $this;
    }

    public function getToSee(): ?string
    {
        return $this->toSee;
    }

    public function setToSee(?string $toSee): self
    {
        $this->toSee = $toSee;

        return $this;
    }

    public function getNotSeen(): ?string
    {
        return $this->notSeen;
    }

    public function setNotSeen(?string $notSeen): self
    {
        $this->notSeen = $notSeen;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(?int $year): self
    {
        $this->year = $year;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Sticky{% endblock %}</title>
    {% block stylesheets %} {{ encore_entry_link_tags('app') }}
    <link href="{{ asset('css/main.css') }}" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> {% endblock %}
</head>

<body>
    <div id="sidebar">
        {% block sidebar %}
        <div class="home_menu">
            <a href="{{ path('home') }}"><i class="glyphicon glyphicon-home"></i>HOME</a>
        </div>
        <div class="task_menu">
            <a href="{{ path('task_list') }}"><i class="glyphicon glyphicon-tasks"></i>TASKS</a>
            <a href="{{ path('task_new') }}"><i class="glyphicon glyphicon-edit"></i></a>
        </div>
        <div class="note_menu">
            <a href="{{ path('note_list') }}"><i class="glyphicon glyphicon-list"></i>NOTES</a>
            <a href="{{ path('note_new') }}"><i class="glyphicon glyphicon-edit"></i></a>
        </div>
        <div class="movie_menu">
            <a href="{{ path('movie_list') }}"><i class="glyphicon glyphicon-film"></i>MOVIES</a>
            <a href="{{ path('movie_new') }}"><i class="glyphicon glyphicon-edit"></i></a>
        </div>{% endblock %}
    </div>

    <div id="content">
        {% block body %}{% endblock %}
    </div>
    {% block javascripts %} {{ encore_entry_script_tags('app') }}
    <script src="/build/runtime.js"></script>
    <script src="/build/app.js"></script>
    {% endblock %}
</body>

</html>

templates/home.html.twig
{% extends 'base.html.twig' %} {% block body %}
<div class="note">
    <a href="{{ path('note_list') }}">
        <h1>Notes</h1>
    </a>
    {{ include('note/list.html.twig') }} {# {% for note in notes %}
    <div class="item">
        <div class="details">
            <p class="note_name"> <a href="{{ path('note_show', {'id':note.id}) }}">{{ note.name|e }}</a></p>
        </div>
        <div class="info">
            <p> {{ note.info }} </p>
        </div>
    </div>
    {% endfor %} #}
</div>
<div class="task">
    <a href="{{ path('task_list') }}">
        <h1>Tasks</h1>
    </a>
    {{ include('task/list.html.twig') }} {# {% for task in tasks %}
    <div class="item">
        <div class="details">
            <p class="task_name"> <a href="{{ path('task_show', {'id':task.id}) }}">{{ task.name|e }}</a></p>
            <p> {{ task.dueDate|date('d/m/y') }} </p>
        </div>
        <div class="info">
            <p> {{ task.info }} </p>
        </div>
    </div>
    {% endfor %} #}
</div>
<div class="movie">
    <a href="{{ path('movie_list') }}">
        <h1>Movies</h1>
    </a>
    {{ include('movie/list.html.twig') }} {# {% for movie in movies %}
    <div class="item">
        <div class="details">
            <p class="movie_name"> <a href="{{ path('movie_show', {'id':movie.omdbId}) }}">{{ movie.omdbId|e }}</a></p>
        </div>
        <div class="info">
            <p> </p>
        </div>
    </div>
    {% endfor %} #}
</div>
{% endblock %}